import type { ImageSourcePropType } from 'react-native';

/**
 * Local movie posters, keyed by catalogue id.
 *
 * GENERATED by scripts/generate-poster-map.mjs — do not edit by hand. Drop a
 * poster named after its catalogue id into assets/images/posters/ and run
 * `npm run posters`.
 *
 * A TMDB key takes precedence over these; without either, the poster falls back
 * to a typographic card.
 */
export const LOCAL_POSTERS: Record<string, ImageSourcePropType> = {

};

export function localPoster(movieId: string): ImageSourcePropType | undefined {
  return LOCAL_POSTERS[movieId];
}
